[versions]
agp = "8.13.0"
android-compileSdk = "36"
android-minSdk = "24"
android-targetSdk = "35"
androidx-activity = "1.11.0"
androidx-core = "1.17.0"

compose-tooling = "1.7.6"
compose-plugin = "1.9.1"
kotlin = "2.2.21"
ksp = "2.2.20-2.0.3"
androidx-room = "2.8.3"
androidx-sqlite-bundled = "2.6.1"
wire = "5.4.0"
coil = "3.3.0"
haze = "1.6.10"

kotlinx-dateTime = "0.7.1"
kotlinx = "1.10.2"

ktor = "3.3.1"
koin = "4.1.1"
koin-compose = "4.1.1"
paging-common = "3.3.6"
image-loader = "1.10.0"
aws-sdk = "1.5.44"
file-picker = "3.1.0"
splash-screen = "1.2.0-rc01"
uuid = "0.8.4"
adaptive = "1.1.2"
kermit = "2.0.8"
navigation-compose = "2.9.1"
lifecycle-viewmodel = "2.9.5"
savedstate = "1.3.5"
kotlin-inject = "0.8.0"
crashkios = "0.9.0"
firebase-crashlytics = "19.4.4"
firebase-analytics = "23.0.0"
firebase-perf = "22.0.2"
moko-permissions = "0.20.1"
datastore = "1.1.7"
material-kolor = "3.0.1"
androidx-work-runtime = "2.10.5"
store5 = "5.1.0-alpha07"
jmapviewer = "2.24"
filekit = "0.12.0"
play-services-location = "21.3.0"
maps-compose = "6.12.1"
accompanist-permissions = "0.37.3"
play-services-coroutines = "1.10.2"
krossbow = "9.3.0"
firebase-bom = "34.4.0"
firebase-auth = "24.0.1"
google-services = "4.4.4"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-activity = { module = "androidx.activity:activity", version.ref = "androidx-activity" }
androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }

splash-screen = { module = "androidx.core:core-splashscreen", version.ref = "splash-screen" }

koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin-compose" }
koin-compose-viewmodel = { module = "io.insert-koin:koin-compose-viewmodel", version.ref = "koin-compose" }

kotlinx-dateTime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-dateTime" }

ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-auth = { module = "io.ktor:ktor-client-auth", version.ref = "ktor" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-client-okHttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-serialization = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-contentNegotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-websockets = { module = "io.ktor:ktor-client-websockets", version.ref = "ktor" }
ktor-serialization-kotlinx-xml = { module = "io.ktor:ktor-serialization-kotlinx-xml", version.ref = "ktor" }

krossbow-stomp-core = { module = "org.hildan.krossbow:krossbow-stomp-core", version.ref = "krossbow" }
krossbow-websocket-ktor = { module = "org.hildan.krossbow:krossbow-websocket-ktor", version.ref = "krossbow" }
krossbow-stomp-kxserialization = { module = "org.hildan.krossbow:krossbow-stomp-kxserialization", version.ref = "krossbow" }


paging-common = { module = "androidx.paging:paging-common", version.ref = "paging-common" }
paging-componse-common = { module = "androidx.paging:paging-compose", version.ref = "paging-common" }

room-runtime = { module = "androidx.room:room-runtime", version.ref = "androidx-room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "androidx-room" }
room-paging = { module = "androidx.room:room-paging", version.ref = "androidx-room" }
sqlite-bundled = { module = "androidx.sqlite:sqlite-bundled", version.ref = "androidx-sqlite-bundled" }

image-loader = { module = "io.github.qdsfdhvh:image-loader", version.ref = "image-loader" }

kermit = { group = "co.touchlab", name = "kermit", version.ref = "kermit" }
kotlin-inject-runtime = { group = "me.tatarka.inject", name = "kotlin-inject-runtime", version.ref = "kotlin-inject" }
crashkios-crashlytics = { group = "co.touchlab.crashkios", name = "crashlytics", version.ref = "crashkios" }
google-firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics-ktx", version.ref = "firebase-crashlytics" }
google-firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics", version.ref = "firebase-analytics" }
google-firebase-perf = { group = "com.google.firebase", name = "firebase-perf", version.ref = "firebase-perf" }

moko-permissions-core = { module = "dev.icerock.moko:permissions", version.ref = "moko-permissions" }
moko-permissions-compose = { module = "dev.icerock.moko:permissions-compose", version.ref = "moko-permissions" }

aws-s3 = { group = "aws.sdk.kotlin", name = "s3", version.ref = "aws-sdk" }
file-picker = { group = "com.darkrockstudios", name = "mpfilepicker", version.ref = "file-picker" }
uuid = { group = "com.benasher44", name = "uuid", version.ref = "uuid" }
material3-adaptive = { group = "org.jetbrains.compose.material3.adaptive", name = "adaptive", version.ref = "adaptive" }
material3-adaptive-layout = { group = "org.jetbrains.compose.material3.adaptive", name = "adaptive-layout", version.ref = "adaptive" }
material3-adaptive-navigation = { group = "org.jetbrains.compose.material3.adaptive", name = "adaptive-navigation", version.ref = "adaptive" }
navigation-compose = { group = "org.jetbrains.androidx.navigation", name = "navigation-compose", version.ref = "navigation-compose" }
lifecycle-viewmodel = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel", version.ref = "lifecycle-viewmodel" }
savedstate = { group = "org.jetbrains.androidx.savedstate", name = "savedstate", version.ref = "savedstate" }
savedstate-compose = { group = "org.jetbrains.androidx.savedstate", name = "savedstate-compose", version.ref = "savedstate" }
datastore = { group = "androidx.datastore", name = "datastore", version.ref = "datastore" }
datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore" }

kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx" }
wire-runtime = { group = "com.squareup.wire", name = "wire-runtime", version.ref = "wire" }

coil-core = { module = "io.coil-kt.coil3:coil-core", version.ref = "coil" }
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
coil-network = { module = "io.coil-kt.coil3:coil-network-ktor3", version.ref = "coil" }

haze = { module = "dev.chrisbanes.haze:haze", version.ref = "haze" }
material-kolor = { module = "com.materialkolor:material-kolor", version.ref = "material-kolor" }

androidx-work-runtime = { module = "androidx.work:work-runtime-ktx", version.ref = "androidx-work-runtime" }

store5 = { module = "org.mobilenativefoundation.store:store5", version.ref = "store5" }
jmapviewer = { module = "org.openstreetmap.jmapviewer:jmapviewer", version.ref = "jmapviewer" }

filekit-core = { module = "io.github.vinceglb:filekit-core", version.ref = "filekit" }
filekit-dialogs = { module = "io.github.vinceglb:filekit-dialogs", version.ref = "filekit" }
filekit-dialogs-compose = { module = "io.github.vinceglb:filekit-dialogs-compose", version.ref = "filekit" }

play-services-location = { module = "com.google.android.gms:play-services-location", version.ref = "play-services-location" }
play-services-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services", version.ref = "play-services-coroutines" }
maps-compose = { module = "com.google.maps.android:maps-compose", version.ref = "maps-compose" }
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist-permissions" }

# Native Firebase for Android
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase-bom" }
firebase-auth = { module = "com.google.firebase:firebase-auth", version.ref = "firebase-auth" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
room = { id = "androidx.room", version.ref = "androidx-room" }
wire = { id = "com.squareup.wire", version.ref = "wire" }
googleServices = { id = "com.google.gms.google-services", version.ref = "google-services" }
kotlinCocoapods = { id = "org.jetbrains.kotlin.native.cocoapods", version.ref = "kotlin" }

[bundles]
ktor-common = ["ktor-client-core", "ktor-client-logging", "ktor-client-serialization", "ktor-client-contentNegotiation", "ktor-client-auth", "ktor-client-cio", "ktor-client-websockets"]
krossbow = ["krossbow-stomp-core", "krossbow-websocket-ktor", "krossbow-stomp-kxserialization"]
